# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "google" {
  project = var.project
  region  = var.region
  zone    = var.zone
}

provider "google-beta" {
  project = var.project
  region  = var.region
  zone    = var.zone
}
